#!/usr/bin/python3

import yaml
import re
import os.path
import subprocess
from os import environ, getenv, getcwd
from html.parser import HTMLParser
from urllib.request import urlopen
from collections import OrderedDict, Counter
from yaml.resolver import BaseResolver
import urllib.request
import base64

class AndroidImagesParser(HTMLParser):

    def __init__(self, config):
        HTMLParser.__init__(self)
        self.config = config
        self.devices = self.config['devices'].keys()
        self.version = self.config['version']
        self.version_open = False
        self.hash_pattern = re.compile(r'\b[0-9a-f]{64}\b')
        self.images = {}
        self.image = {}
        self.build = False
        self.variant = False
        self.device = False

    def handle_starttag(self, tag, attrs):
        if tag == 'tr':
            for attr in attrs:
                if attr[0] == 'id':
                    for device in self.devices:
                        if attr[1].startswith(device):
                            self.image = {}
                            self.device = device

    def handle_data(self, data):
        if self.device:
            if len(data) > 6:
                if self.hash_pattern.match(data) \
                and self.version_open == True:
                    self.image['factory_hash'] = data
                elif data.split(' ')[0].startswith("%s." % self.version):
                    self.version_open = True
                    tokens = data.split(" ")
                    self.image['factory_build'] = \
                        tokens[1].replace("(","").replace(",", "")
                    variant = tokens[4:5]
                    if variant:
                        self.variant = variant[0].replace(")","").lower()
                    else:
                        self.variant = "global"

    def handle_endtag(self, tag):
        if tag == 'tr' and self.device and self.variant:
            if self.version_open == True:
                self.images.setdefault(
                    self.device,{}
                )[self.variant] = self.image
                self.version_open = False
            self.device = False
            self.build = False
            self.variant = False

def dict_representer(dumper, data):
    return dumper.represent_dict(data.items())
def dict_constructor(loader, node):
    return OrderedDict(loader.construct_pairs(node))
yaml.add_representer(OrderedDict, dict_representer)
yaml.add_constructor(BaseResolver.DEFAULT_MAPPING_TAG, dict_constructor)

if __name__ == "__main__":

    config_file='%s/config.yml' % getcwd()
    with open(config_file, encoding='utf-8') as data_file:
        config = yaml.load(data_file.read())

    all_tags = []
    platform_build_url = "https://android.googlesource.com/platform/build"
    tag_filter = "android-{}".format(config['version'])
    process = subprocess.run(["git", "ls-remote", "--refs", "--tags", "--sort=v:refname", platform_build_url], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    for line in process.stdout.split(b'\n'):
        tag = line.decode().split('/')[-1]
        if tag_filter in tag:
            all_tags.append(tag)
    latest_tags = all_tags[-5:]

    build_id_tags = {}
    build_id_git_url = "https://android.googlesource.com/platform/build/+/refs/tags/{}/core/build_id.mk?format=TEXT"
    build_id_filter = "BUILD_ID="
    for tag in latest_tags:
        output = base64.decodebytes(urllib.request.urlopen(build_id_git_url.format(tag)).read()).decode()
        for line in output.split('\n'):
            if build_id_filter in line:
                build_id = line.split(build_id_filter)[1]
                build_id_tags[build_id] = tag

    image_url = "https://developers.google.com/android/images"
    image_html = urlopen(image_url).read()
    image_parser = AndroidImagesParser(config)
    image_parser.images = {}
    image_parser.feed(str(image_html))

    for device in config['devices']:
        for variant, values in image_parser.images[device].items():
            for key, value in values.items():
                config['devices'].setdefault(
                    device,{}
                )[key] = value

            # TODO: i'm guessing we want to support all variants?
            if variant == "global":
                factory_build = values['factory_build']
                if factory_build in build_id_tags:
                    config['devices'].setdefault(device, {})['platform_ref'] = build_id_tags[factory_build]
                else:
                    print("Unable to find latest build tag for factory build {} for device {}".format(factory_build, device))

    with open(config_file, 'w') as outfile:
        yaml.dump(config, outfile, default_flow_style=False)
